### ISSUE TITLE
Failed to connect user to tiktok

### ISSUE THREAD

**Issue by noambert** [nglmercer/Tiktok-Live-APPv3#5]
![dasd](https://github.com/nglmercer/Tiktok-Live-TTS-APPv2/assets/144626648/6bb2f756-a0cc-400e-8c1b-90283fbede0a)
 
The problem occurred 3 days ago.

**Comment by nglmercer** [comment]
No problem, I'll fix that, it's a server issue, it doesn't take more than a few minutes to update the libraries to make it work again.
If it fails again don't hesitate to report the issue
