### ISSUE TITLE
Features that don't work

### ISSUE THREAD

**Issue by noambert** [nglmercer/Tiktok-Live-APPv3#6]
In Sounds you cannot add a sound manually. 
Nothing appears in the Tiktok gifts theme and Overlays appear empty.

[
![Captura de pantalla 2024-05-29 183801](https://github.com/nglmercer/Tiktok-Live-TTS-APPv2/assets/144626648/9c0faa02-099c-4bb9-acee-1b48d29af3a6)
![Captura de pantalla 2024-05-29 183817](https://github.com/nglmercer/Tiktok-Live-TTS-APPv2/assets/144626648/c09c50cb-1d3f-4c40-8c3e-7dcb312974b9)
![Captura de pantalla 2024-05-29 183831](https://github.com/nglmercer/Tiktok-Live-TTS-APPv2/assets/144626648/e8c10a58-9b5c-4ae4-9ad9-a5c95d90bead)
](url)

**Comment by nglmercer** [comment]
![image](https://github.com/nglmercer/Tiktok-Live-TTS-APPv2/assets/128845117/b656931c-714d-4958-8bb9-208ff4a9cdfd)
I'm working on the overlays, they don't work because I'm improving them, so there's nothing and the sounds should work perfectly.

**Comment by noambert** [comment]
> ![imagen](https://private-user-images.githubusercontent.com/128845117/335028199-b656931c-714d-4958-8bb9-208ff4a9cdfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwOTIzOTksIm5iZiI6MTcxNzA5MjA5OSwicGF0aCI6Ii8xMjg4NDUxMTcvMzM1MDI4MTk5LWI2NTY5MzFjLTcxNGQtNDk1OC04YmI5LTIwOGZmNGE5Y2RmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMFQxODAxMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDBlMzc0ZDFmMTBhZGRmZTVlMjE3NjQ5OTA3NmFjOWI1OGFkMDJiZjZmODdkYjljM2RkMTI3MDE3YTZlMmYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5KWp7z6_XjhoXVP0wmIsdJ5-lqatKPAKkjmqebuVHkQ) Estoy trabajando en los overlays, no funcionan porque los estoy mejorando, así que no hay nada y los sonidos deberían funcionar perfectamente.

If the sounds work, what is not available is adding your own custom sounds.
